[package]
name = "moji"
version = "0.1.0"
authors = ["Michael DeMarco <michaelfromyeg@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.13"
anyhow = "1.0"
indicatif = "0.16.0"